package com.slark.pengder.mybatis.model;

import java.util.Date;

public class TRemoteShutdownRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_shutdown_record.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_shutdown_record.UserID
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_shutdown_record.UserRole
     *
     * @mbg.generated
     */
    private Integer userrole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_shutdown_record.CardSerial
     *
     * @mbg.generated
     */
    private Integer cardserial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_shutdown_record.InstrumentID
     *
     * @mbg.generated
     */
    private Integer instrumentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_shutdown_record.BookingId
     *
     * @mbg.generated
     */
    private Integer bookingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_shutdown_record.Status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_shutdown_record.AddTime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_remote_shutdown_record.AddIp
     *
     * @mbg.generated
     */
    private String addip;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    public TRemoteShutdownRecord(Integer id, Integer userid, Integer userrole, Integer cardserial, Integer instrumentid, Integer bookingid, Byte status, Date addtime, String addip) {
        this.id = id;
        this.userid = userid;
        this.userrole = userrole;
        this.cardserial = cardserial;
        this.instrumentid = instrumentid;
        this.bookingid = bookingid;
        this.status = status;
        this.addtime = addtime;
        this.addip = addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    public TRemoteShutdownRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_shutdown_record.ID
     *
     * @return the value of t_remote_shutdown_record.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_shutdown_record.ID
     *
     * @param id the value for t_remote_shutdown_record.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_shutdown_record.UserID
     *
     * @return the value of t_remote_shutdown_record.UserID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_shutdown_record.UserID
     *
     * @param userid the value for t_remote_shutdown_record.UserID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_shutdown_record.UserRole
     *
     * @return the value of t_remote_shutdown_record.UserRole
     *
     * @mbg.generated
     */
    public Integer getUserrole() {
        return userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_shutdown_record.UserRole
     *
     * @param userrole the value for t_remote_shutdown_record.UserRole
     *
     * @mbg.generated
     */
    public void setUserrole(Integer userrole) {
        this.userrole = userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_shutdown_record.CardSerial
     *
     * @return the value of t_remote_shutdown_record.CardSerial
     *
     * @mbg.generated
     */
    public Integer getCardserial() {
        return cardserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_shutdown_record.CardSerial
     *
     * @param cardserial the value for t_remote_shutdown_record.CardSerial
     *
     * @mbg.generated
     */
    public void setCardserial(Integer cardserial) {
        this.cardserial = cardserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_shutdown_record.InstrumentID
     *
     * @return the value of t_remote_shutdown_record.InstrumentID
     *
     * @mbg.generated
     */
    public Integer getInstrumentid() {
        return instrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_shutdown_record.InstrumentID
     *
     * @param instrumentid the value for t_remote_shutdown_record.InstrumentID
     *
     * @mbg.generated
     */
    public void setInstrumentid(Integer instrumentid) {
        this.instrumentid = instrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_shutdown_record.BookingId
     *
     * @return the value of t_remote_shutdown_record.BookingId
     *
     * @mbg.generated
     */
    public Integer getBookingid() {
        return bookingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_shutdown_record.BookingId
     *
     * @param bookingid the value for t_remote_shutdown_record.BookingId
     *
     * @mbg.generated
     */
    public void setBookingid(Integer bookingid) {
        this.bookingid = bookingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_shutdown_record.Status
     *
     * @return the value of t_remote_shutdown_record.Status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_shutdown_record.Status
     *
     * @param status the value for t_remote_shutdown_record.Status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_shutdown_record.AddTime
     *
     * @return the value of t_remote_shutdown_record.AddTime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_shutdown_record.AddTime
     *
     * @param addtime the value for t_remote_shutdown_record.AddTime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_remote_shutdown_record.AddIp
     *
     * @return the value of t_remote_shutdown_record.AddIp
     *
     * @mbg.generated
     */
    public String getAddip() {
        return addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_remote_shutdown_record.AddIp
     *
     * @param addip the value for t_remote_shutdown_record.AddIp
     *
     * @mbg.generated
     */
    public void setAddip(String addip) {
        this.addip = addip == null ? null : addip.trim();
    }
}