package com.slark.pengder.mybatis.dao;

import com.slark.pengder.mybatis.model.TRemoteShutdownRecord;
import com.slark.pengder.mybatis.model.TRemoteShutdownRecordExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface TRemoteShutdownRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    long countByExample(TRemoteShutdownRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    int deleteByExample(TRemoteShutdownRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_remote_shutdown_record",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_remote_shutdown_record (ID, UserID, ",
        "UserRole, CardSerial, ",
        "InstrumentID, BookingId, ",
        "Status, AddTime, ",
        "AddIp)",
        "values (#{id,jdbcType=INTEGER}, #{userid,jdbcType=INTEGER}, ",
        "#{userrole,jdbcType=INTEGER}, #{cardserial,jdbcType=INTEGER}, ",
        "#{instrumentid,jdbcType=INTEGER}, #{bookingid,jdbcType=INTEGER}, ",
        "#{status,jdbcType=TINYINT}, #{addtime,jdbcType=TIMESTAMP}, ",
        "#{addip,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=true, resultType=Integer.class)
    int insert(TRemoteShutdownRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    int insertSelective(TRemoteShutdownRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    List<TRemoteShutdownRecord> selectByExample(TRemoteShutdownRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, UserID, UserRole, CardSerial, InstrumentID, BookingId, Status, AddTime, ",
        "AddIp",
        "from t_remote_shutdown_record",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.slark.pengder.mybatis.dao.TRemoteShutdownRecordMapper.BaseResultMap")
    TRemoteShutdownRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TRemoteShutdownRecord record, @Param("example") TRemoteShutdownRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TRemoteShutdownRecord record, @Param("example") TRemoteShutdownRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TRemoteShutdownRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remote_shutdown_record
     *
     * @mbg.generated
     */
    @Update({
        "update t_remote_shutdown_record",
        "set UserID = #{userid,jdbcType=INTEGER},",
          "UserRole = #{userrole,jdbcType=INTEGER},",
          "CardSerial = #{cardserial,jdbcType=INTEGER},",
          "InstrumentID = #{instrumentid,jdbcType=INTEGER},",
          "BookingId = #{bookingid,jdbcType=INTEGER},",
          "Status = #{status,jdbcType=TINYINT},",
          "AddTime = #{addtime,jdbcType=TIMESTAMP},",
          "AddIp = #{addip,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TRemoteShutdownRecord record);
}